[package]
name = "tippe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
fs-err = "2.9.0"
geo = "0.25.0"
geo-types = "0.7.8"
geojson = { version= "0.24.1", features=["geo-types"] }
mvt = "0.8.1"
pmtiles2 = "0.2.0"
pointy = "0.4.0"
rstar = "0.11.0"
serde_json = "1.0.107"
